const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(require('path').join(__dirname,'../app.js'),'utf8');
function boot(saved){
 const globals=new Map(),screenNodes=[];let storage=saved?JSON.stringify(saved):null;
 const node=(attrs='')=>{
  const n={style:{},dataset:{},value:'',textContent:'',disabled:false,checked:false,focused:false,classList:{toggle:()=>false,remove(){}},setAttribute(){},focus(){this.focused=true;}};
  for(const m of attrs.matchAll(/data-([a-z]+)(?:="([^"]*)")?/g))n.dataset[m[1]]=m[2]||"";
  n.id=attrs.match(/\bid="([^"]*)"/)?.[1];n.disabled=/\bdisabled\b/.test(attrs);
  let html='';Object.defineProperty(n,'innerHTML',{get:()=>html,set:value=>{
   html=value;if(n===globals.get('#screen')){
    screenNodes.length=0;
    for(const m of value.matchAll(/<(?:textarea|button|input)\b([^>]*)>/g))screenNodes.push(node(m[1]));
   }
  }});
  return n;
 };
 for(const id of ['title','stepCount','bar','nav','back','next','screen','reset','mobileNavToggle'])globals.set('#'+id,node());
 const doc={
  querySelector:s=>globals.get(s)||screenNodes.find(n=>s==='#'+n.id)||null,
  querySelectorAll:s=>{const key=s.match(/^\[data-([a-z]+)\]$/)?.[1];return key?screenNodes.filter(n=>key in n.dataset):[];},
  getElementById:id=>globals.get('#'+id)||screenNodes.find(n=>n.id===id)||null
 };
 const ctx={document:doc,localStorage:{getItem:()=>storage,setItem:(k,v)=>storage=v},window:{scrollTo(){}},navigator:{clipboard:{writeText:async()=>{}}},confirm:()=>true,console,Blob,URL};
 vm.createContext(ctx);vm.runInContext(source,ctx);
 return {run:code=>vm.runInContext(code,ctx),doc,reload:()=>boot(JSON.parse(storage)),stored:()=>JSON.parse(storage)};
}
let b=boot(),r=b.run;
assert.equal(r('steps[6]'),"The Devil's Advocate");
assert.equal(r('data.devilsAdvocate.outcomes.length'),1);
assert.equal(r('advocateComplete()'),false);
r('step=6;render()');
let html=b.doc.querySelector('#screen').innerHTML;
for(const copy of ["Looking at your life direction, what would failure in this decision look like?","Could making this choice lead you towards that outcome? If so, how?","I could end up…","Write how it could happen, if you see a connection…","neighbourhood bakery"] )assert(html.includes(copy));
assert(!html.includes('research'));assert(!html.includes('further studies'));assert(!html.includes('Earlier Inversion notes'));
assert.equal((html.match(/<textarea/g)||[]).length,2);
assert(!html.includes('advocate-connection" hidden'));
let fields=b.doc.querySelectorAll('[data-advocatetext]');
fields[0].value='I rarely bake and miss family time';fields[0].oninput();
fields[1].value='Two sites could require me to cover staff absences';fields[1].oninput();
const id=r('data.devilsAdvocate.outcomes[0].id');
assert.equal(r('advocateComplete()'),true);
assert.equal(b.stored().devilsAdvocate.outcomes[0].connection,fields[1].value);
assert.equal(JSON.parse(r('JSON.stringify(reflections())')).filter(x=>x.id.startsWith('devils-advocate-')).length,1);
assert(r('decisionContextText()').includes("## The Devil's Advocate"));
assert(r('decisionContextText()').includes('Possible connection: Two sites'));
assert(r('vulnerabilityItems().join(" ")').includes('I rarely bake'));
assert(r('decisionOverview()').includes('data-edit="6">Review The Devil&#39;s Advocate'));
assert(r('decisionOverview()').includes('Possible connection: Two sites'));
assert.equal(b.doc.querySelector('#addAdvocateOutcome'),null);
assert.equal(b.doc.querySelectorAll('[data-advocatedelete]').length,0);
let responses=b.doc.querySelectorAll('[data-advocateresponse]');
assert.equal(responses.length,2);
responses[0].onclick();
assert.equal(r('data.devilsAdvocate.outcomes[0].connectionResponse'),'unknown');
assert(r('advocateComplete()'));
assert.equal(r('advocateInvestigations().length'),1);
assert(r('allInvestigations().join(" ")').includes('Explore whether'));
assert(r('decisionOverview()').includes('Review The Devil&#39;s Advocate unknown'));
assert(b.doc.getElementById('advocate-'+id+'-connection').disabled);
assert(b.doc.getElementById('advocate-'+id+'-unknown').focused);
html=b.doc.querySelector('#screen').innerHTML;
assert(html.includes('aria-pressed="true"'));
assert(r('decisionContextText()').includes('Connection assessment (your view): I do not know yet'));
assert(r('decisionContextText()').includes('Earlier connection writing (retained; not the current response)'));
assert(!r('reflections().find(x=>x.id==="devils-advocate-'+id+'").text').includes('Two sites'));
let unknownReload=b.reload();unknownReload.run('step=6;render()');
assert.equal(unknownReload.run('data.devilsAdvocate.outcomes[0].connectionResponse'),'unknown');
assert(unknownReload.doc.getElementById('advocate-'+id+'-connection').disabled);
b.doc.querySelectorAll('[data-advocateresponse]')[1].onclick();
assert.equal(r('data.devilsAdvocate.outcomes[0].connectionResponse'),'no');
assert.equal(r('advocateInvestigations().length'),0);
assert.equal(r('vulnerabilityItems().length'),0);
assert(r('decisionOverview()').includes('Your connection assessment'));
assert(r('decisionOverview()').includes('No, I don’t see this choice leading towards that outcome'));
assert(r('decisionContextText()').includes('not proof that the choice is safe'));
assert(r('advocateComplete()'));
assert.equal(b.reload().run('data.devilsAdvocate.outcomes[0].connectionResponse'),'no');
b.doc.querySelectorAll('[data-advocatewrite]')[0].onclick();
assert.equal(r('data.devilsAdvocate.outcomes[0].connectionResponse'),'');
assert(!b.doc.getElementById('advocate-'+id+'-connection').disabled);
assert(b.doc.getElementById('advocate-'+id+'-connection').focused);
assert.equal(r('data.devilsAdvocate.outcomes[0].connection'),'Two sites could require me to cover staff absences');
b.doc.querySelectorAll('[data-advocateresponse]')[0].onclick();
b.doc.querySelectorAll('[data-advocateresponse]')[0].onclick();
assert.equal(r('data.devilsAdvocate.outcomes[0].connectionResponse'),'');
assert(!b.doc.getElementById('advocate-'+id+'-connection').disabled);
r('data.devilsAdvocate.outcomes[0].connection=""');assert(!r('advocateComplete()'));
r('data.devilsAdvocate.outcomes[0].connectionResponse="no"');assert(r('advocateComplete()'));
r('data.devilsAdvocate.outcomes[0].outcome=""');assert(!r('advocateComplete()'));
r('data.devilsAdvocate.outcomes[0].outcome="I rarely bake and miss family time";data.devilsAdvocate.outcomes[0].connection="Two sites could require me to cover staff absences";data.devilsAdvocate.outcomes[0].connectionResponse="";save()');
let reloaded=b.reload();assert.equal(reloaded.run('data.devilsAdvocate.outcomes[0].connection'),'Two sites could require me to cover staff absences');
reloaded.run('data.reviewed.push(6);save()');assert(reloaded.reload().run('data.reviewed.includes(6)'));
let old=JSON.parse(r('JSON.stringify(fresh())'));delete old.devilsAdvocate;old.inversion=['Original failure condition',''];old.reviewed=[0,1,2,3,4,5,6,7,8,9,10];
old.factors=[{id:'saved-driver',name:'Original driver',options:[],sources:[{id:'inversion-0',text:'Original failure condition',optionId:null}],importance:3,evidence:1,strength:1}];
let migrated=boot(old);
assert.deepEqual(JSON.parse(migrated.run('JSON.stringify(data.inversion)')),old.inversion);
assert.equal(migrated.run('data.devilsAdvocate.outcomes[0].outcome'),'');
assert(!migrated.run('data.reviewed.includes(6)'));assert(migrated.run('data.reviewed.includes(5)'));assert(migrated.run('data.reviewed.includes(7)'));
assert.equal(migrated.run('data.factors[0].sources[0].id'),'inversion-0');
assert(migrated.run('decisionContextText()').includes('Earlier Inversion notes (retained; original failure-condition question)'));
assert(migrated.run('reflections().some(x=>x.id==="inversion-0")'));
migrated.run('data.reviewed.push(6);save()');assert(migrated.reload().run('data.reviewed.includes(6)'));
let previous=JSON.parse(r('JSON.stringify(fresh())'));
previous.devilsAdvocate={formatVersion:1,outcomes:[{id:'first',outcome:'First outcome',connection:'First route'},{id:'second',outcome:'Second outcome',connection:'Second route'}]};
previous.reviewed=[5,6,7];
previous.factors=[{id:'linked',name:'Linked',sources:[{id:'devils-advocate-second',text:'Second route',optionId:null}]}];
let converted=boot(previous);
assert.equal(converted.run('data.devilsAdvocate.formatVersion'),2);
assert.equal(converted.run('data.devilsAdvocate.outcomes.length'),1);
assert.equal(converted.run('data.devilsAdvocate.outcomes[0].id'),'first');
assert.equal(converted.run('data.devilsAdvocate.outcomes[0].connection'),'First route');
assert.equal(converted.run('data.devilsAdvocate.earlierOutcomes[0].id'),'second');
assert.equal(converted.run('data.factors[0].sources[0].id'),'devils-advocate-second');
assert(converted.run('reflections().some(x=>x.id==="devils-advocate-second")'));
assert(converted.run('decisionContextText()').includes('Earlier additional outcome reflections (retained)'));
assert(converted.run('decisionContextText()').includes('Second route'));
assert(!converted.run('data.reviewed.includes(6)'));
converted.run('step=6;render()');assert.equal((converted.doc.querySelector('#screen').innerHTML.match(/<textarea/g)||[]).length,2);
converted.run('data.reviewed.push(6);save()');
let again=converted.reload();assert(again.run('data.reviewed.includes(6)'));
assert.equal(again.run('data.devilsAdvocate.earlierOutcomes.length'),1);
r('data.devilsAdvocate.outcomes[0].outcome="<script>bad</script>";data.devilsAdvocate.outcomes[0].connection="<img src=x onerror=bad>"');
assert(!r('inversion()').includes('<script>bad'));assert(!r('decisionOverview()').includes('<img src=x'));
r('data.devilsAdvocate.outcomes[0].outcome="A concrete outcome";data.devilsAdvocate.outcomes[0].connection="I do not see a plausible connection"');assert(r('advocateComplete()'));
r('data.options[0].name="Bakery expansion";data.decisionAim="Increase income";data.hasHardBoundaries="no";data.priorities=[lifeDomains[0].id];data.stakes=[lifeDomains[0].id];data.reviewed=Array.from({length:11},(_,i)=>i);const o=choiceOption();o.trade.alternatives=["Keep one bakery"];o.trade.immediate="Time";o.trade.future="Flexibility";compoundingQuestions.forEach(q=>o.compound[q.key]="Reflection");o.consequence.immediate="More customers";["favourable","unfavourable"].forEach(k=>{o.consequence.branchEnded[k]=true;o.consequence.branches[k]=["Possible effect"]});o.reverse.difficulty=1;data.factors=[{id:"f",name:"Time",importance:3,evidence:2,strength:1,directionAssessed:true,options:[],sources:[]}];stressRows.forEach(row=>data.stressTest.ratings[row.id]={[o.id]:"manageable"});');
assert(r('assessmentComplete()'));r('data.devilsAdvocate.outcomes[0].connection=""');assert(!r('assessmentComplete()'));r('data.devilsAdvocate.outcomes[0].connectionResponse="unknown"');assert(r('assessmentComplete()'));assert(r('analyse().unresolved')>0);r('data.devilsAdvocate.outcomes[0].connectionResponse="no"');assert(r('assessmentComplete()'));assert.equal(r('advocateInvestigations().length'),0);
for(let i=0;i<12;i++){r('step='+i+';render()');assert(b.doc.querySelector('#screen').innerHTML.length>0);}
r('step=6;render()');b.doc.querySelector('#back').onclick();assert.equal(r('step'),5);
r('step=6;render()');b.doc.querySelector('#next').onclick();assert.equal(r('step'),7);
b.doc.querySelector('#reset').onclick();assert.equal(r('step'),0);assert.equal(r('data.devilsAdvocate.outcomes.length'),1);assert.equal(r('data.devilsAdvocate.outcomes[0].outcome'),'');
assert.equal(r('data.inversion[0]'),'');
console.log('Passed: one fixed pair, mutually exclusive response toggles, disabled/restored writing and focus, save/reload/reset, prior-pair and legacy migration/source preservation, one-time review reset, Drivers/Overview/export semantics, unresolved unknowns, completeness, escaping, all 12 screens and navigation.');
